### ISSUE TITLE
error listing: directory not found

### ISSUE THREAD

**Issue by theminor** [ttionya/vaultwarden-backup#196]
I know I must be doing something wrong but I just can't get my configuration to work. Here is my `compose.yaml`:

```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vw.mysite.com
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=xxxx-xxxx-xxxx-xxxx-xxxx
      - PUSH_INSTALLATION_KEY=xxxxx
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURITY=force_tls
      - SMTP_FROM=xxx@gmail.com
      - SMTP_USERNAME=xxx@gmail.com
      - SMTP_PASSWORD=xxxx
    volumes:
      - ./vw-data/:/data/
    ports:
      - 11111:80

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
 
volumes:
  vaultwarden-data:
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
 ```

And `rclone` seems to be working fine:
```bash
sudo docker run --rm -it \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  ttionya/vaultwarden-backup:latest \
  rclone config show
[BitwardenBackup]
type = drive
token = {"access_token":"xxxxx","token_type":"Bearer","refresh_token":"xxxx"}
team_drive = 
```

I've also tried with a `OneDrive` implementation of `rclone` with the same result.

Attempting to run a manual backup to test things, I get the following error:

```bash
sudo docker run \                    
  --rm \
  --name vaultwarden_backup \
  --volumes-from=vaultwarden \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  --env DATA_DIR='/data' \
  ttionya/vaultwarden-backup:latest backup
========================================
DATA_DIR: /data
DATA_CONFIG: /data/config.json
DATA_RSAKEY: /data/rsa_key
DATA_ATTACHMENTS: /data/attachments
DATA_SENDS: /data/sends
========================================
DB_TYPE: SQLITE
DATA_DB: /data/db.sqlite3
========================================
CRON: 5 * * * *
RCLONE_REMOTE: BitwardenBackup:/BitwardenBackup
RCLONE_GLOBAL_FLAG: 
ZIP_ENABLE: TRUE
ZIP_PASSWORD: 18 Chars
ZIP_TYPE: zip
BACKUP_FILE_DATE_FORMAT: %Y%m%d (example "[filename].20250509.[ext]")
BACKUP_KEEP_DAYS: 0
MAIL_SMTP_ENABLE: FALSE
TIMEZONE: UTC
DISPLAY_NAME: vaultwarden
========================================
2025/05/09 01:33:46 ERROR : : error listing: directory not found
2025/05/09 01:33:46 NOTICE: Failed to lsd with 2 errors: last error was: directory not found
storage system connection failure [BitwardenBackup:/BitwardenBackup]
storage system connection failure exists
```

I see that some directory is not found but I can't figure out what is missing. I've been over the `readme.md` multiple times. I'm sure it is something obvious. Any assistance would be appreciated!

**Comment by ttionya** [comment]
It has been confirmed that there is an error in the program, which was introduced when fixing #183.

I will fix this error after I go back in a few days.

Now you need to manually create /BitwardenBackup in the storage, such as in OneDrive. This should solve the problem.

**Comment by theminor** [comment]
Thanks - that fixed it for the manual backup. However, the automatic backups are still not working. I revised my my `compose.yaml` as follows:
```yaml
services:
  vaultwarden:
    [...unchanged...]

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    volumes:
      - ./vw-data/:/bitwarden/data/.
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
 
volumes:
  vaultwarden-data:
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
```

With no `CRON` env variable set, this should mean the backup should run at 5 minutes past every hour, but it doesn't seem to be running at all.  I see nothing about vaultwarden backups in the vaultwarden logs:
```bash
sudo docker logs vaultwarden

/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.33.2                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://github.com/dani-garcia/vaultwarden/discussions or        |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[2025-05-09 15:19:30.129][start][INFO] Rocket has launched from http://0.0.0.0:80
[2025-05-09 15:19:45.899][request][INFO] GET /api/config
[2025-05-09 15:19:45.899][response][INFO] (config) GET /api/config => 200 OK
...
[2025-05-09 16:17:08.906][vaultwarden::api::notifications][INFO] Closing WS connection from 192.168.1.27
[2025-05-09 16:17:12.122][vaultwarden::api::notifications][INFO] Closing WS connection from 192.168.1.27
[2025-05-09 17:07:23.282][request][INFO] GET /notifications/hub?access_token=xxxxxxx
[2025-05-09 17:07:23.283][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 192.168.1.27
....
```

Does vaultwarden-backup have a separate log or is there a way to increase the logging level? Thanks again for your help - I realize you are traveling, so no rush!

**Comment by ttionya** [comment]
You need to delete the vaultwarden-data volume because you have already mapped the local folder.

And you have also added an incorrect dot.

services:
  vaultwarden:
    [...unchanged...]

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    volumes:
      - ./vw-data/:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
 
volumes:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data

**Comment by theminor** [comment]
Still not triggering at the CRON time and no mention in the logs...

```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://vw.mysite.com
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=xxxx-xxxx-xxxx-xxxx-xxxx
      - PUSH_INSTALLATION_KEY=xxxxx
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURITY=force_tls
      - SMTP_FROM=xxx@gmail.com
      - SMTP_USERNAME=xxx@gmail.com
      - SMTP_PASSWORD=xxxxx
    volumes:
      - ./vw-data/:/data/
    ports:
      - 11111:80

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      RCLONE_REMOTE_NAME: 'VaultwardenBackup'
      RCLONE_REMOTE_DIR: '/VaultwardenBackup/'
      ZIP_PASSWORD: 'xxx'
      ZIP_TYPE: '7z'
      BACKUP_KEEP_DAYS: 30
      TIMEZONE: 'America/New_York'
      DISPLAY_NAME: 'VaultwardenBackup'
      CRON: '23 * * * *'
    volumes:
      - ./vw-data/:/bitwarden/data/
      - vaultwarden-rclone-data:/config/

volumes:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
```

For testing, I just change the `CRON` to an upcoming time, hence `23` in this case.

Logs:
```bash
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.33.2                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://github.com/dani-garcia/vaultwarden/discussions or        |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[2025-05-10 18:20:46.645][start][INFO] Rocket has launched from http://0.0.0.0:80
[2025-05-10 18:22:54.985][request][INFO] GET /notifications/hub?access_token=xxxxx
[2025-05-10 18:22:54.985][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 192.168.1.27
[2025-05-10 18:22:54.986][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[2025-05-10 18:24:53.381][request][INFO] GET /notifications/hub?access_token=xxxxx
[2025-05-10 18:24:53.382][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 192.168.1.27
[2025-05-10 18:24:53.382][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[2025-05-10 18:28:43.110][request][INFO] GET /notifications/hub?access_token=xxxxx
[2025-05-10 18:28:43.111][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 192.168.1.27
[2025-05-10 18:28:43.111][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
```

Thanks again for the help. Hopefully it is something obvious!

**Comment by ttionya** [comment]
Environment variables need to be `NAME=VALUE`

**Comment by ttionya** [comment]
I can't see any errors; the container prints the environment variables in yellow text after a successful start. If there is no output from vaultwarden-backup in the logs, I think the container might have terminated abnormally.

1. Confirm that the container is running and not exiting for some reason.
2. If you are using ARM, please refer to #53

Looking forward to your feedback.

**Comment by theminor** [comment]
Strange. Yes, the container continues to run and is still running and I'm able to use Vaultwarden just fine. And no, my architecture is `X86_64`. And `date` reports the correct time and date.

I always restart the container with `sudo docker compose up -d vaultwarden` and then `sudo docker compose restart vaultwarden` just for good measure. I don't see any logs at all for `VaultwardenBackup` from `sudo docker logs vaultwarden`.

Any other ideas?

**Comment by ttionya** [comment]
Oh, do you know the difference between `docker compose up -d` and `docker compose up -d vaultwarden`?

If not, try `sudo docker compose down && sudo docker compose up -d && sudo docker compose logs -f`.
